name: Spring 21 - Export Pluto notebooks & Deploy
on:
    push:
        branches:
            - Spring21
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1.5
            - name: Run Pluto notebooks
              run: julia -e 'import Pkg;
                  env = mktempdir();
                  Pkg.activate(env);
                  Pkg.add([
                  Pkg.PackageSpec(url="https://github.com/fonsp/PlutoUtils.jl", rev="ac10069"),
                  Pkg.PackageSpec(url="https://github.com/fonsp/Pluto.jl", rev="9edb7b2"),
                  ]);
                  import PlutoUtils;

                  PlutoUtils.Export.github_action(; export_dir=".", offer_binder=true);'
            - name: Franklin
              run: julia -e '
                  using Pkg;
                  Pkg.add(["NodeJS", "JSON", "Franklin"]);
                  using NodeJS;

                  cp("notebooks", "website/notebooks");
                  cd("website");

                  run(`$(npm_cmd()) install highlight.js`);
                  using Franklin;
                  optimize();
                  mkdir("__site2");
                  mv("__site", "__site2/Spring21");
                  write("__site2/index.html", """
                  <!DOCTYPE html>
                  <html>
                  <head><meta charset="utf-8"><script>
                  window.location.href=\"Spring21\"</script></head>
                  <body></body></html>""");'
            - name: Build and Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: Spring21-franklin-output
                  FOLDER: website/__site2
